source 'https://github.com/Tovema-iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'TMMasonryExtends_Example' do
  pod 'TMMasonryExtends', :path => '../'
  pod 'CYLDeallocBlockExecutor'

  target 'TMMasonryExtends_Tests' do
    inherit! :search_paths

    
  end
end
